language: node_js

node_js:
- 6.9

cache:
  directories:
  - node_modules

install:
- npm install

script:
- npm test
- npm run lint
- npm run build

after_success:
- ls -lha
- bash <(curl -s https://codecov.io/bash)
